[config]
# Global settings (mandatory)
default_mode = 'dark'
default_type = 'scheme-tonal-spot'

[templates.colors]
input_path = '/home/tim/.config/matugen/templates/colors.css'
output_path = '/home/tim/.cache/matugen/colors.css'

[templates.foot]
input_path = '~/.config/matugen/templates/foot.conf'
output_path = '~/.config/foot/colors.ini'